title: "Data Mining for Business Analytics"
description: "By Xiaorui Zhu <br /> The greatest truths are the simplest. -- Tao Te Ching <br /> Thinking details thoughtfully, solving in whole elegantly. -- Xiaorui Zhu"
show_downloads: FALSE
theme: jekyll-theme-cayman
google_analytics: []
markdown: kramdown